Repository prokuranepal/miras-backend, pull requests merged in 2022-05, with the labels that each got.

#122 Add celery for asynchronous tasks.
  common/utils.py
  miras/__init__.py
  miras/celery.py
  miras/settings.py
  requirements.txt
Labels: enhancement

#125 Display exam details for unenrolled users.
  exams/api/serializers.py
  exams/api/urls.py
  exams/api/utils.py
  exams/api/views.py
Labels: bug

#127 profile page bug
  accounts/api/serializers.py
  enrollments/api/serializers.py
Labels: bug

#130 Record the test submission.
  enrollments/api/serializers.py
  enrollments/migrations/0009_examstatus_submitted.py
  enrollments/models.py
  exams/api/serializers.py
Labels: bug, enhancement

#132 Export enrollment with celery using actions.
  enrollments/admin.py
  enrollments/models.py
  miras/settings.py
Labels: bug

#134 Update Content, Recorded video, course
  content/api/serializers.py
  content/migrations/0006_auto_20220515_0505.py
  content/migrations/0007_recordedvideo_detail.py
  content/migrations/0008_auto_20220515_0709.py
  content/models.py
  courses/api/serializers.py
  courses/migrations/0017_auto_20220515_0520.py
  courses/models.py
Labels: bug

#135 Removed notes from part
  accounts/api/serializers.py
  accounts/api/urls.py
  accounts/api/views.py
  courses/migrations/0020_merge_0017_auto_20220515_0520_0019_auto_20220515_0723.py
  notes/admin.py
  notes/api/views.py
  notes/migrations/0007_remove_note_part.py
  notes/models.py
  part/admin.py
  part/api/serializers.py
Labels: bug

#136 Create profile on signal
  accounts/admin.py
  accounts/migrations/0013_auto_20220516_1621.py
  accounts/signals.py
  common/decorators.py
Labels: bug
